#
# Vivado (TM) v2016.2 (64-bit)
#
# Project.tcl: Tcl script for re-creating project 'xy1en1om_win'
#
# Generated by Vivado on Thu Aug 04 22:17:47 +0200 2016
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (Project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/rtl/axi_wr_fifo.v"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/rtl/axi_slave.v"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/rtl/axi_master.v"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/rtl/red_pitaya_ps.v"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/rtl/red_pitaya_hk.v"
#    "C:/Users/espero/git/RedPitaya_RadioBox/fpga/bd/hdl/system_wrapper.v"
#    "C:/Users/espero/git/RedPitaya_RadioBox/fpga/bd/system.bd"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/rtl/red_pitaya_rst_clken.sv"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/rtl/regs.sv"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/rtl/top.sv"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/rtl/axi_pc2leds.v"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/rtl/keccak_f1600_round.sv"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/rtl/sha256_engine.sv"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/ip/adc_clk_pll/adc_clk_pll.xci"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/ip/fifo_64i_512o_128d/fifo_64i_512o_128d.xci"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/sdc/project.xdc"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/tbn/sys_bus_model.sv"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/tbn/axi_master_model.sv"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/tbn/red_pitaya_pll_tb.sv"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/tbn/red_pitaya_hk_tb.sv"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/tbn/axi_slave_tb.sv"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/tbn/regs_sha256_tb.sv"
#    "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/sim/regs_sha256_tb_behav.wcfg"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "Project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/project"]"

# Create project
create_project xy1en1om_win ./xy1en1om_win -part xc7z010clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects xy1en1om_win]
set_property "corecontainer.enable" "1" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "generate_ip_upgrade_log" "0" $obj
set_property "part" "xc7z010clg400-1" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "source_mgmt_mode" "DisplayOnly" $obj
set_property "xpm_libraries" "XPM_CDC XPM_MEMORY" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/axi_wr_fifo.v"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/axi_slave.v"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/axi_master.v"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/red_pitaya_ps.v"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/red_pitaya_hk.v"]"\
 "[file normalize "$origin_dir/../../../../git/RedPitaya_RadioBox/fpga/bd/hdl/system_wrapper.v"]"\
 "[file normalize "$origin_dir/../../../../git/RedPitaya_RadioBox/fpga/bd/system.bd"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/red_pitaya_rst_clken.sv"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/regs.sv"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/top.sv"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/axi_pc2leds.v"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/keccak_f1600_round.sv"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/sha256_engine.sv"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/ip/adc_clk_pll/adc_clk_pll.xci"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/ip/fifo_64i_512o_128d/fifo_64i_512o_128d.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../../../git/RedPitaya_RadioBox/fpga/bd/system.bd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "0" $file_obj
}

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/red_pitaya_rst_clken.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/regs.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/keccak_f1600_round.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/rtl/sha256_engine.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/ip/adc_clk_pll/adc_clk_pll.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "0" $file_obj
}

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/ip/fifo_64i_512o_128d/fifo_64i_512o_128d.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "0" $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "top" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/sdc/project.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/sdc/project.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/sdc/project.xdc"]" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/sys_bus_model.sv"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/axi_master_model.sv"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/red_pitaya_pll_tb.sv"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/red_pitaya_hk_tb.sv"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/axi_slave_tb.sv"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/regs_sha256_tb.sv"]"\
 "[file normalize "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/sim/regs_sha256_tb_behav.wcfg"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/sys_bus_model.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/axi_master_model.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/red_pitaya_pll_tb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/red_pitaya_hk_tb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/axi_slave_tb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../../../../git/DF4IAH_xy1en1om/fpga/tbn/regs_sha256_tb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "regs_sha256_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.more_options" "-v 2" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj
set_property "xsim.elaborate.xelab.more_options" "-v 2" $obj
set_property "xsim.view" "C:/Users/espero/git/DF4IAH_xy1en1om/fpga/sim/regs_sha256_tb_behav.wcfg" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z010clg400-1 -flow {Vivado Synthesis 2016} -strategy "Flow_PerfOptimized_high" -constrset constrs_1
} else {
  set_property strategy "Flow_PerfOptimized_high" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7z010clg400-1" $obj
set_property "steps.synth_design.args.fanout_limit" "400" $obj
set_property "steps.synth_design.args.fsm_extraction" "one_hot" $obj
set_property "steps.synth_design.args.keep_equivalent_registers" "1" $obj
set_property "steps.synth_design.args.resource_sharing" "off" $obj
set_property "steps.synth_design.args.no_lc" "1" $obj
set_property "steps.synth_design.args.shreg_min_size" "5" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z010clg400-1 -flow {Vivado Implementation 2016} -strategy "Performance_ExplorePostRoutePhysOpt" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Performance_ExplorePostRoutePhysOpt" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7z010clg400-1" $obj
set_property "steps.opt_design.args.directive" "Explore" $obj
set_property "steps.place_design.args.directive" "Explore" $obj
set_property "steps.phys_opt_design.is_enabled" "1" $obj
set_property "steps.phys_opt_design.args.directive" "Explore" $obj
set_property "steps.route_design.args.directive" "Explore" $obj
set_property -name {steps.route_design.args.more options} -value {-tns_cleanup} -objects $obj
set_property "steps.post_route_phys_opt_design.is_enabled" "1" $obj
set_property "steps.post_route_phys_opt_design.args.directive" "Explore" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:xy1en1om_win"
